name: deeprug
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pygame
  - numpy
  - pip
  - pip:
      - numpy
      - sample-factory
      - matplotlib
      - tqdm
      - torch
      - torchvision
      - torchaudio